SveltyCMS/SveltyCMS

src/components/Collections_latest.svelte
src/components/EntryList.svelte
src/components/Fields.svelte
src/components/Form.svelte
src/lib/stores/fieldStore.ts
src/routes/[[lang]]/+layout.svelte
src/routes/[[lang]]/+page.svelte

**Changes Made**
- Created a Collection_latest component for handling collections logic
- Added popup for collections in sidebar
- Used EntryList component to show tables
- Shifted Form to EntryList component
- Fixed Translation dropdowns
- Added stores for switching forms and entrylist components

Refactored collection to use ListBox and ListBoxItem and shifted Form inside EntryList component and some store changes

---

src/lib/models/sign-up-token-model.ts
src/routes/[[lang]]/login/+page.server.ts
src/routes/[[lang]]/user/+page.server.ts
src/routes/[[lang]]/user/ModalTokenUser.svelte

**Changes Made**
- Updated signup-token model to have expiringAt
- Added check for expiring token while sign up
- Added expiring field in ModelTOkenUser

Updated signup token model and added expiring at functionality

---

src/lib/models/user-model.ts
src/routes/[[lang]]/login/+page.server.ts
src/routes/[[lang]]/user/ModalTokenUser.svelte

**Changes Made**
- Added `expiresAt` in user model
- forgot password link generation
- forgot password token expiry

Forgot password link generation

---

.env.example

Added quotes to "en" and "de" on line 4

Added quotes

---

package.json
src/components/EntryList.svelte
src/lib/stores/entryListTable.ts
src/lib/utils/utils.ts
src/lib/utils/utils_svelte.ts
src/routes/[[lang]]/+layout.svelte
src/routes/[[lang]]/login/components/SigninForm.svelte
src/routes/[[lang]]/user/+page.svelte
src/routes/api/[collection]/+server.ts
src/routes/api/user/editAvatar/+server.ts

Added save functionality and user avatar and multiple wiggle on signin form

---

src/components/AnimatedHamburger.svelte
src/components/EntryList.svelte
src/routes/[[lang]]/+layout.svelte
src/routes/[[lang]]/login/components/SigninForm.svelte
src/routes/[[lang]]/login/components/SignupForm.svelte

- Tweaks in css for EntryList and Sidebar
- added curly braces to signupfrom and signinform
- Hamburger bug where sometimes x would be shown instead of hamburger is fixed

Hamburger buggy fixed + css tweaks

---

src/components/widgets/address/Address.svelte
src/components/widgets/text/Text.svelte

text widget fix
added a condition for address widget (only if api key is given in .env)

Text widget fix

---

src/collections/Test.ts
src/components/widgets/address/Address.svelte
src/components/widgets/currency/Currency.svelte
src/components/widgets/currency/index.ts
src/components/widgets/currency/types.d.ts
src/components/widgets/index.ts
src/components/widgets/remoteVideo/video.ts
src/components/widgets/richText/RichText.svelte
src/components/widgets/richText/types.d.ts
src/components/widgets/text/Text.svelte
src/routes/api/getTokensProvided/+server.ts

-Currency widget added
-Invisible suffix and line appearing fixed
-Address widget form working
-Number widget formatting
-Rich text passing value
-Saving still not working for richtext adn address

Widgets fixes

---

src/collections/Test.ts
src/components/Form.svelte
src/components/widgets/currency/Currency.svelte
src/components/widgets/currency/index.ts

- Currency widget now enforces min and max values to be typed
- Fixed suffix alignment
- Added hamburger to edit page

Currency min-max checker + suffix alignment + hamburger on edit page

---

src/collections/Test.ts
src/components/widgets/address/Address.svelte
src/components/widgets/checkbox/Checkbox.svelte
src/components/widgets/currency/Currency.svelte
src/components/widgets/date/Date.svelte
src/components/widgets/dateRange/DateRange.svelte
src/components/widgets/email/Email.svelte
src/components/widgets/group/Group.svelte
src/components/widgets/imageArray/ImageArray.svelte
src/components/widgets/imageUpload/ImageUpload.svelte
src/components/widgets/radio/Radio.svelte
src/components/widgets/remoteVideo/RemoteVideo.svelte
src/components/widgets/richText/RichText.svelte
src/components/widgets/selectList/SelectList.svelte
src/components/widgets/selectList/type.d.ts

- Zod validation done on most widgets
- Select widget options work now

Zod validation on most widgets

---

src/collections/Test.ts
src/components/Fields.svelte
src/components/widgets/address/index.ts
src/components/widgets/checkbox/Checkbox.svelte
src/components/widgets/checkbox/index.ts
src/components/widgets/currency/index.ts
src/components/widgets/date/index.ts
src/components/widgets/dateRange/index.ts
src/components/widgets/email/index.ts
src/components/widgets/group/index.ts
src/components/widgets/imageArray/index.ts
src/components/widgets/imageUpload/index.ts
src/components/widgets/megaMenu/index.ts
src/components/widgets/number/index.ts
src/components/widgets/phoneNumber/index.ts
src/components/widgets/radio/Radio.svelte
src/components/widgets/radio/index.ts
src/components/widgets/relation/index.ts
src/components/widgets/remoteVideo/index.ts
src/components/widgets/richText/index.ts
src/components/widgets/selectList/index.ts
src/components/widgets/seo/index.ts
src/components/widgets/text/index.ts
src/components/widgets/url/index.ts
src/lib/i18n/de/index.ts
src/lib/i18n/en/index.ts
src/lib/i18n/i18n-types.ts
src/routes/[[lang]]/+layout.svelte

- Labels for widgets are no longer same as db_Fieldname
- Updating languages still needs to be fixed
- Fixed the light/dark mode tooltip

Widget labels now work, tooltip fix

---

src/collections/Test.ts
src/components/CollectionsList.svelte
src/components/EntryList.svelte
src/components/Form.svelte
src/components/widgets/address/Address.svelte
src/components/widgets/address/index.ts
src/components/widgets/currency/Currency.svelte
src/components/widgets/currency/index.ts
src/components/widgets/currency/types.d.ts
src/components/widgets/remoteVideo/RemoteVideo.svelte
src/components/widgets/richText/RichText.svelte
src/components/widgets/richText/global.css
src/lib/LocaleSwitcher.svelte
src/lib/emails/welcomeUser.svelte
src/lib/utils/utils.ts
src/routes/[[lang]]/+layout.svelte
src/routes/[[lang]]/login/+page.server.ts
src/routes/[[lang]]/login/+page.svelte
src/routes/emails/welcome/+page.server.ts

- Saving for widgets
- Mapbox almost done
- Richtext darkmode
- LocaleSwitcher
- Hamburger disappear on show left sidebar
- Redirect from user works to route

Weekend work

---

inlang.config.js

Hi @Rar9,
this should fix the issue you had when making changes in the Inlang editor.
> Note, it is possible that the CDN caches the link for a few hours. So if it is not working, just wait until tomorrow.

Update plugin in inlang.config.js

---

src/lib/server/lucia.ts
src/routes/[[lang]]/+page.server.ts
src/routes/[[lang]]/chat/+page.server.ts
src/routes/[[lang]]/gallery/+page.server.ts
src/routes/[[lang]]/login/+page.server.ts
src/routes/[[lang]]/login/components/SignupForm.svelte
src/routes/[[lang]]/user/+page.server.ts
src/routes/[[lang]]/user/+page.svelte
src/routes/[[lang]]/user/ModalEditAvatar.svelte
src/routes/[[lang]]/user/ModalEditForm.svelte
src/routes/[[lang]]/user/UserList/UserList.svelte
src/routes/[[lang]]/user2/+page.server.ts

This PR moves the signout functionality to a single function.
It also adds the welcome email to be sent to the admin user.

Fix lucia upgrade pain points

---

src/components/IconifyPicker.svelte

the icon picker is now fully functional with default icon picker library as google icons material and the drop down is also closing when user select and icon and user can also see their selected icon, changing the library category from select change also directly changes the icons

icon picker is fully functional now

---

src/routes/(app)/collection/Column.svelte

original category name are not showing undefined now

fix edit category modal bug 

---

package.json
src/auth/index.ts
src/auth/types.ts
src/routes/(app)/[language]/+layout.server.ts
src/routes/(app)/dashboard/+page.server.ts
src/routes/+page.server.ts
src/routes/api/databases/db.ts
src/routes/login/+page.server.ts

1. Change user_id to _id whereever used
2. Change Google auth to config based

signin issue

---

src/auth/mongoDBAuth/sessionAdapter.ts
src/auth/mongoDBAuth/tokenAdapter.ts
src/auth/mongoDBAuth/userAdapter.ts
src/databases/dbInterface.ts
src/databases/mongodb/dbconnect.ts
src/databases/mongodb/models/contentStructure.ts
src/databases/mongodb/models/draft.ts
src/databases/mongodb/models/media.ts
src/databases/mongodb/models/revision.ts
src/databases/mongodb/models/systemPreferences.ts
src/databases/mongodb/models/systemVirtualFolder.ts
src/databases/mongodb/models/theme.ts
src/databases/mongodb/models/widget.ts
src/databases/mongodb/mongoDBAdapter.ts
src/utils/logger.svelte.ts

Fix: Db initialization

---

src/routes/(app)/[language]/[...collection]/+page.svelte

In the collections page, while changing system language, the page was encountering an infinite loading. The infinite loading is fixed.

chore: improve data fetching logic in collection page to optimize loading state

---

bun.lock
package.json
src/components/LeftSidebar.svelte
src/components/ParaglideSvelteKit.svelte
src/components/RightSidebar.svelte
src/messages/da.json
src/messages/de.json
src/messages/es.json
src/messages/fi.json
src/messages/fr.json
src/messages/hi.json
src/messages/it.json
src/messages/ja.json
src/messages/ka.json
src/messages/ne.json
src/messages/nl.json
src/messages/no.json
src/messages/pl.json
src/messages/pt.json
src/messages/sl.json
src/messages/sr.json
src/messages/sv.json
src/messages/tr.json
src/messages/ur.json
src/messages/zh.json
src/routes/api/user/createToken/+server.ts
src/stores/store.svelte.ts
vite.config.ts

- Upgraded @inlang/paraglide-js to version 2.0.13 and updated related imports in the project.
- Refactored language handling in components to use getLocale instead of languageTag for improved consistency.
- Updated various package versions in package.json and bun.lock for better compatibility and performance.
- Fixed formatting issues in multiple language JSON files for clarity.

chore: update dependencies and refactor Paraglide integration

---

bun.lock
src/components/EntryList.svelte
src/components/Fields.svelte
src/components/system/table/TableFilter.svelte
src/stores/store.svelte.ts
src/utils/data.ts
src/utils/utils.ts
src/widgets/core/input/Input.svelte

Fix Fields.svelte to save data
